### ISSUE TITLE
NotSupportedException when passing Func

### ISSUE THREAD

**Issue by grubyrychu** [artem-sedykh/Sprint.Filter.OData#1]
```
 Func<SearchResult, bool> priceMaxFunc = result => result.Price <= 30
 return Filter.Serialize<SearchResult>(priceMaxFunc);
```

**Comment by grubyrychu** [comment]
I also want to be able to build Func like so:

`Func<SearchResult, bool> priceMaxFunc = result => result.Price <= 30;
            Func<SearchResult, bool> priceMinFunc = result => result.Price >= 10;
            Func<SearchResult, bool> sum = result => priceMinFunc(result) && priceMaxFunc(result);`

**Comment by artem-sedykh** [comment]
Expression<Func<SearchResult, bool>> priceMaxFunc = result => result.Price <= 30;
            Expression<Func<SearchResult, bool>> priceMinFunc = result => result.Price >= 10;

            //add reference Sprint.Linq nuget https://www.nuget.org/packages/Sprint.Linq            
            var summ = priceMaxFunc.And(priceMinFunc);

            //Price le 30m and Price ge 10m
            var expr = Sprint.Filter.OData.Filter.Serialize(summ);
