### ISSUE TITLE
Case insensitive properties

### ISSUE THREAD

**Issue by friendly-tech** [artem-sedykh/Sprint.Filter.OData#4]
Could we support case insensitive properties, often my DTO property is

`public string SomethingName { get; set; }`

But when serialized to json is presented to user as `somethingName`

I dont want user to have to pass SomethingName into odata query when he knows it as somethingName

Something like..

```
private static MemberInfo ResolveAliasInternal(Type type, string alias)
    {
      ....
        if (String.Equals(x.Name, alias, StringComparison.OrdinalIgnoreCase))
          return x;
        return (MemberInfo) null;
      })).FirstOrDefault<MemberInfo>((Func<MemberInfo, bool>) (x => x != (MemberInfo) null));
    }

```

Yes i can use DataContract, but i dont want to...

**Comment by artem-sedykh** [comment]
I decided to make IMemberNameProvider, now you can redefine it to fit your needs, available in version 1.3.2

**Comment by friendly-tech** [comment]
Awesome, now i can get ride of my super nasty reflection hack...

**Comment by friendly-tech** [comment]
Just tried to use this, and notice your constructor for `QueryTranslator` ignores the passed in parameter.

`public QueryTranslator(IMemberNameProvider memberNameProvider)
        {
            _memberNameProvider = new DefaultMemberNameProvider();
        }`


It should be

`public QueryTranslator(IMemberNameProvider memberNameProvider)
        {
            _memberNameProvider = memberNameProvider ?? new DefaultMemberNameProvider();
        }`
